# Environment (Run First Section)

In [ ]:
!pip install transformers datasets py7zr evaluate rouge_score tqdm --quiet

In [ ]:
!pip install --upgrade --quiet langchain-text-splitters tiktoken

In [ ]:
from langchain_text_splitters import TokenTextSplitter
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from langchain.text_splitter import TokenTextSplitter
from google.colab import files
import json
from huggingface_hub import notebook_login
from datasets import load_dataset
from nltk.tokenize import sent_tokenize
import evaluate
from rouge_score import rouge_scorer
import nltk
from langchain.chains.summarize import load_summarize_chain
from langchain_huggingface import HuggingFacePipeline
from tqdm.notebook import tqdm

In [ ]:
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
nltk.download('punkt')

scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=False)

In [ ]:
datasets = [load_dataset("ccdv/arxiv-summarization"), load_dataset("ccdv/pubmed-summarization"), load_dataset("ccdv/govreport-summarization")]
datasets

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

[DatasetDict({
     train: Dataset({
         features: ['article', 'abstract'],
         num_rows: 203037
     })
     validation: Dataset({
         features: ['article', 'abstract'],
         num_rows: 6436
     })
     test: Dataset({
         features: ['article', 'abstract'],
         num_rows: 6440
     })
 }),
 DatasetDict({
     train: Dataset({
         features: ['article', 'abstract'],
         num_rows: 119924
     })
     validation: Dataset({
         features: ['article', 'abstract'],
         num_rows: 6633
     })
     test: Dataset({
         features: ['article', 'abstract'],
         num_rows: 6658
     })
 }),
 DatasetDict({
     train: Dataset({
         features: ['report', 'summary'],
         num_rows: 17517
     })
     validation: Dataset({
         features: ['report', 'summary'],
         num_rows: 973
     })
     test: Dataset({
         features: ['report', 'summary'],
         num_rows: 973
     })
 })]

# Testing (Don't need to run)

In [ ]:
for i, ds in enumerate(datasets):
  if i == 2:
    test_summaries = [ds['test'][i]['summary'] for i in range(len(ds['test']))]
  else:
    test_summaries = [ds['test'][i]['abstract'] for i in range(len(ds['test']))]
  lens = [len(sum) for sum in test_summaries]
  print(f"Dataset {i}: {sum(lens)/len(lens)}")

Dataset 0: 966.4517080745342
Dataset 1: 1252.1004806248122
Dataset 2: 3851.4850976361768

In [ ]:
facebook_summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
fb_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
google_summarizer = pipeline("summarization", model="google/pegasus-large")
google_tokenizer = AutoTokenizer.from_pretrained("google/pegasus-large")
t5_summarizer = pipeline("summarization", model="Falconsai/text_summarization")
t5_tokenizer = AutoTokenizer.from_pretrained("Falconsai/text_summarization")

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-large and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
def first_tokens(article):
    bart_tokens_tensor = fb_tokenizer(article, return_tensors="pt").input_ids[0][:512]
    pegasus_tokens_tensor = google_tokenizer(article, return_tensors="pt").input_ids[0][:512]
    t5_tokens_tensor = t5_tokenizer(article, return_tensors="pt").input_ids[0][:512]
    bart_tokens = bart_tokens_tensor.tolist()
    pegasus_tokens = pegasus_tokens_tensor.tolist()
    t5_tokens = t5_tokens_tensor.tolist()
    bart_tokens = fb_tokenizer.convert_tokens_to_string(fb_tokenizer.convert_ids_to_tokens(bart_tokens))
    pegasus_tokens = google_tokenizer.convert_tokens_to_string(google_tokenizer.convert_ids_to_tokens(pegasus_tokens))
    t5_tokens = t5_tokenizer.convert_tokens_to_string(t5_tokenizer.convert_ids_to_tokens(t5_tokens))
    return bart_tokens, pegasus_tokens, t5_tokens

In [ ]:
results = {"datasets": [{"name": "ccdv/arxiv-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}, {"name": "ccdv/pubmed-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}, {"name": "ccdv/govreport-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}]}

In [ ]:
test_indexes = [0, 10, 20]
rouge_scores = {"fb":[], "google":[], "t5":[]}
for i, ds in enumerate(datasets):
  print(f"{i}  ", end='\r')
  if i == 2:
    article_text = "report"
    sum_text = "summary"
  else:
    article_text = "article"
    sum_text = "abstract"
  for ex_idx in test_indexes:
    print(i, ex_idx)
    article = ds['test'][ex_idx][article_text]
    true_summary = ds['test'][ex_idx][sum_text]
    bart_article, pegasus_article, t5_article = first_tokens(article)
    summaries = {"fb":[], "google":[], "t5":[]}
    fb_summary = str(facebook_summarizer(bart_article, max_length=300, min_length=25, do_sample=False)[0]["summary_text"])
    google_summary = str(google_summarizer(pegasus_article, max_length=300, min_length=25, do_sample=False)[0]["summary_text"])
    t5_summary = str(t5_summarizer(t5_article, max_length=300, min_length=25, do_sample=False)[0]["summary_text"])
    results["datasets"][i]["models"]["bert"][ex_idx] = scorer.score(true_summary, fb_summary)
    results["datasets"][i]["models"]["pegasus"][ex_idx] = scorer.score(true_summary, google_summary)
    results["datasets"][i]["models"]["t5"][ex_idx] = scorer.score(true_summary, t5_summary)
    print("t5", t5_summary)
    print("true", true_summary)
results

0 0
t5 for about 20 years the problem of properties of short- term changes of solar activity has been considered extensively . many investigators studied the short - term periodicities of the various indices of solar activities . several periodicities were detected , but the periodicities about 155 days and from the interval of @xmath3 $ $ ] days ( @Xmath4 $ $] years ) are mentioned most often . first of them was discovered by @xcite in the occurence rate of gamma -
true the short - term periodicities of the daily sunspot area fluctuations from august 1923 to october 1933 are discussed . for these data
 the correlative analysis indicates negative correlation for the periodicity of about @xmath0 days , but the power spectrum analysis indicates a statistically significant peak in this time interval .
 a new method of the diagnosis of an echo - effect in spectrum is proposed and it is stated that the 155-day periodicity is a harmonic of the periodicities from the interval of @xmath1 $ ] days .    the autocorrelation functions for the daily sunspot area fluctuations and for the fluctuations of the one rotation time interval in the northern hemisphere , separately for the whole solar cycle 16 and for the maximum activity period of this cycle do not show differences , especially in the interval of @xmath2 $ ] days .
 it proves against the thesis of the existence of strong positive fluctuations of the about @xmath0-day interval in the maximum activity period of the solar cycle 16 in the northern hemisphere .
 however , a similar analysis for data from the southern hemisphere indicates that there is the periodicity of about @xmath0 days in sunspot area data in the maximum activity period of the cycle 16 only .
0 10
t5 entanglement @xcite in a composite system refers to certain implicit correlation between the subsystems arising from their interaction . it is the key resource of quantum computation and quantum information processing @xcita . due to recent advances in this field , en Tanglement has generated renewed interest . there have been different approaches to understand and to quantify enthitlement @Xcite . but so far the engtanglement , only in . a bipartite pure state has been investigated very extensively
true strong subadditivity inequality for a three - particle composite system is an important inequality in quantum information theory which can be studied via a four - particle entangled state .
 we use two three - level atoms in @xmath0 configuration interacting with a two - mode cavity and the raman adiabatic passage technique for the production of the four - particle entangled state . using this four - particle entanglement
 , we study for the first time various aspects of the strong subadditivity inequality .
0 20
t5 it has been known for a long time that the classical two - integral equilibrium theory in axisymmetric geometry is not sufficient to adequately describe the stellar discs of galaxies . in accordance with jeans theorem ( jeans 1915 ) , the phase space distribution function of a stellar system in a steady state depends only on the isolating integrals of the motion .
true we present new equilibrium component distribution functions that depend on three analytic integrals in a stckel potential , and that can be used to model stellar discs of galaxies .
 these components are generalizations of two - integral ones and can thus provide thin discs in the two - integral approximation .
 their most important properties are the partly analytical expression for their moments , the disc - like features of their configuration space densities ( exponential decline in the galactic plane and finite extent in the vertical direction ) and the anisotropy of their velocity dispersions .
 we further show that a linear combination of such components can fit a van der kruit disc .
 epsf rotate    = =    = =    = =    = =    # 1 # 1    # 1 # 1    @mathgroup@group    @mathgroup@normal@groupeurmn    @mathgroup@bold@groupeurbn    @mathgroup@group    @mathgroup@normal@groupmsamn    @mathgroup@bold@groupmsamn    = " 019    = " 016    = " 040    = " 336    = " 33e    = =    = =    = =    = =    # 1 # 1    # 1 # 1    = =    = =    = =    = =    [ firstpage ]    galaxies : kinematics and dynamics  galaxies : stucture  stars : kinematics .
1 0
t5 anxiety affects quality of life in those living with parkinson 's disease ( pd ) more so than overall cognitive status , motor deficits , apathy , and depression [ 13 ] . although anxiety and depression are often related and coexist in ppd patients , recent research suggests that anxiety rather than depression is the most prominent and prevalent mood disorder . yet, our current understanding of anxiety and its impact on cognition in pD , as well as its neural basis and best treatment practices
true research on the implications of anxiety in parkinson 's disease ( pd ) has been neglected despite its prevalence in nearly 50% of patients and its negative impact on quality of life .
 previous reports have noted that neuropsychiatric symptoms impair cognitive performance in pd patients ; however , to date , no study has directly compared pd patients with and without anxiety to examine the impact of anxiety on cognitive impairments in pd .
 this study compared cognitive performance across 50 pd participants with and without anxiety ( 17 pda+ ; 33 pda ) , who underwent neurological and neuropsychological assessment .
 group performance was compared across the following cognitive domains : simple attention / visuomotor processing speed , executive function ( e.g. , set - shifting ) , working memory , language , and memory / new verbal learning .
 results showed that pda+ performed significantly worse on the digit span forward and backward test and part b of the trail making task ( tmt - b ) compared to the pda group .
 there were no group differences in verbal fluency , logical memory , or tmt - a performance . in conclusion ,
 anxiety in pd has a measurable impact on working memory and attentional set - shifting .
1 10
t5 male macroprolactinomas ( mprl ) are usually revealed by headaches , visual troubles and gonadal insufficiency . suppurative meningitis ( sm ) , a life - threatening condition .
true background : suppurative meningitis ( sm ) or bacterial meningitis is a life - threatening condition , which is exceptionally due to pituitary tumors ( pt ) . our aim was to analyze its frequency among male macroprolactinomas ( mprl ) deemed to be aggressive , to report the cases we observed in our practice and describe the circumstances under which sm appeared.materials and methods : we retrospectively analyzed 82 male mprl in order to look for a history of well proved sm and the circumstances under which sm appeared .
 we also took into account the possibility of sm relapsing.results:four out of 82 male mprl had sm = 4.87% .
 three consulted for sm symptoms .
 sm was confirmed in infectious diseases department , but only one had rhinorrhea . hormonal assessment and
 cerebral magnetic resonance imaging pleaded for aggressive prolactinomas .
 after antibiotics , sm was sterilized .
 then , mprl were treated with bromocriptine , which normalized prolactin and reduced pt .
 sm never relapsed .
 the 4th case was hospitalized for a large multidirectional prolactinoma invading and/or arising from the skull base .
 he was operated on 3 times and then he was given bromocriptine .
 after 3 months , he had rhinorrhea and then sm which was successfully treated by antibiotics .
 sm never relapsed after tumor reduction.conclusion:sm was demonstrated in 4.87% .
 sm has revealed mprl in 3 cases and appeared after bromocriptine intake in the 4th one .
 endocrinologists should be aware of this severe condition , which can be avoided by repairing as soon as possible the bony defect secondary to aggressive tumors , unless it is clogged by fibrosis : what probably happened in our cases .
1 20
t5 moraxella catarrhalis is a gram - negative , aerobic diplococcus human mucosal pathogen which causes middle ear infections in infants and children . it is one of the three major causes of otitis media along with streptococcus pneumonia and haemophilus influenzae .
true a bioassay - guided fractionation of methanol extract of aristolochia bracteolata whole plant was carried out in order to evaluate its antimicrobial activity and to identify the active compounds in this extract .
 antibacterial and antifungal activities of methanol extract against gram - positive , gram - negative , and fungal strains were investigated by the agar disk diffusion method . among the strains tested , moraxella catarrhalis and sea urchin - derived bacillus sp .
 showed the highest sensitivity towards the methanol extract and hence they are used as test organisms for the bioassay - guided fractionation . from this
 extract , aristolochic acid 1 ( aa-1 ) has been isolated and has showed the greatest antibacterial activity against both standard strain and clinical isolates of moraxella catarrhalis with equal minimum inhibitory concentration ( mic ) and minimum bactericidal concentration ( mbc ) values of 25 and 50  g / ml . modification of the aa-1 to aa-1 methyl ester completely abolished the antibacterial activity of the compound and the piperonylic acid moiety of aa-1 which suggested that the coexistence of phenanthrene ring and free carboxylic acid is essential for aa-1 antibacterial activity .
2 0
t5 In our prior work, we have found that technological innovation involves not only creating new ideas but also translating those ideas into a new product or service . FDA and USDA have responsibility for overseeing the safety of the food supply . USDA and FDA carry out their responsibilities in part through inspections of facilities where food is produced . The frequency of inspections the agencies conduct varies as follows: FDA .
true Multiple firms have produced cell-cultured meat as part of their research and development. These products appear likely to become available to consumers in coming years. FDA and USDA are the primary agencies responsible for overseeing the safety of the nation's food supply. However, some stakeholders have expressed concern about the agencies' oversight of cell-cultured meat amidst a fragmented federal food safety oversight system. GAO was asked to review federal oversight of cell-cultured meat. This report (1) describes what is known about methods for commercially producing cell-cultured meat, and (2) examines the extent to which FDA and USDA are collaborating to provide regulatory oversight of cell-cultured meat. GAO conducted a literature review; reviewed documentation from FDA, USDA, and stakeholder groups; analyzed public comments submitted to the agencies; compared agency efforts with leading practices for interagency collaboration; and conducted site visits to selected cell-cultured meat firms. General information about the process of making cell-cultured meat—food products grown from the cells of livestock, poultry, and seafood—is available. However, no company is commercially producing cell-cultured meat. Specific information about the technology being used, eventual commercial production methods, and composition of the final products is not yet known. The general process contains five phases: biopsy, cell banking, growth, harvest, and food processing (see figure). The technology and methods to be used for commercial production are still in development, and producers, regulators, and consumers do not have clarity about many specifics about the process and final product. For example, it is unclear whether production methods and products will use or contain genetically-engineered cells or medications such as antibiotics. The Food and Drug Administration (FDA) and U.S. Department of Agriculture (USDA) have begun collaborating on regulatory oversight of cell-cultured meat. For example, in 2019, the agencies signed an interagency agreement and created three working groups to carry out the terms of the agreement. However, the agreement and working groups could more fully incorporate practices to enhance and sustain collaboration, such as defining outcomes. For example, the agreement identifies the development of labeling principles as an outcome, but does not describe how the agencies will track and monitor progress toward this outcome, and the working groups identify a lead agency but not members' roles. Also, agency officials said they decided FDA would oversee cell-cultured seafood other than catfish, but they have not formally announced or documented this decision. Developing and updating written guidance and agreements is also a leading practice for interagency collaboration. By fully incorporating leading practices into their efforts to collaborate, the agencies could minimize potential overlap and fragmentation, use resources in a more efficient manner, and better ensure the public and other key stakeholders have clarity about the agencies' oversight responsibilities. GAO recommends that FDA and USDA more fully incorporate leading practices for effective collaboration in the agencies' interagency agreement. FDA and USDA partially concurred and indicated a willingness to incorporate these practices in a more detailed agreement, which would also meet the intent of the recommendations. The agencies concurred with the four other recommendations.
2 10
t5 In our June 2019 report, we found that abuse deficiencies cited in nursing homes were relatively rare from 2013 through 2017, with the largest increase in severe cases . In addition, abuse deficiencies more than doubled—from 430 in 2013 to 875 in 2017—over the 5-year period . We found that CMS cannot readily access data on the type of abuse or type of perpetrator .
true Nationwide, about 1.4 million elderly or disabled individuals receive care in more than 15,500 nursing homes. CMS, an agency within the Department of Health and Human Services (HHS), defines standards nursing homes must meet to participate in the Medicare and Medicaid programs. Nursing home residents often have physical or cognitive limitations that can leave them particularly vulnerable to abuse. Abuse of nursing home residents can occur in many forms—including physical, mental, verbal, and sexual—and can be committed by staff, residents, or others in the nursing home. Any incident of abuse is a serious occurrence and can result in potentially devastating consequences for residents, including lasting mental anguish, serious injury, or death. This statement summarizes GAO's June 2019 report, GAO-19-433 . Specifically, it describes: (1) the trends and types of abuse in recent years, and (2) CMS's oversight intended to ensure residents are free from abuse. It also includes a brief summary of findings and recommendations from this June 2019 report and prior GAO reports that examined the health and welfare of the elderly in multiple settings, and the status, as of November 2019, of HHS's efforts to implement the recommendations GAO made. The Centers for Medicare & Medicaid Services (CMS) is responsible for ensuring nursing homes meet federal quality standards, including that residents are free from abuse. CMS enters into agreements with state survey agencies to conduct surveys of the state's homes and to investigate complaints and incidents. GAO's June 2019 report found that, while abuse deficiencies cited in nursing homes were relatively rare from 2013 through 2017, they more than doubled during that time, increasing from 430 in 2013 to 875 in 2017, with the largest increase in severe cases. In light of the increased number and severity of abuse deficiencies, it is imperative that CMS have strong nursing home oversight in place to protect residents from abuse. However, GAO found oversight gaps that may limit the agency's ability to do so. Specifically, GAO found: (1) Information on abuse and perpetrator types is not readily available. CMS's data do not allow for the type of abuse or perpetrator to be readily identified by the agency. Specifically, CMS does not require the state survey agencies to record abuse and perpetrator type and, when this information is recorded, it cannot be easily analyzed by CMS. GAO made a recommendation that CMS require state survey agencies to submit data on abuse and perpetrator type and HHS concurred. As of November 2019, HHS had not implemented the recommendation. (2) Facility-reported incidents lack key information. Despite federal law requiring nursing homes to self-report allegations of abuse and covered individuals to report reasonable suspicions of crimes against residents, CMS has not provided guidance to nursing homes on what information they should include in facility-reported incidents, contributing to a lack of information for state survey agencies and delays in their investigations. GAO made a recommendation that CMS develop guidance on what abuse information nursing homes should self-report and HHS concurred. As of November 2019, HHS had not implemented the recommendation. (3) Gaps exist in the CMS process for state survey agency referrals to law enforcement. GAO found gaps in CMS's process for referring incidents of abuse to law enforcement. These gaps may limit CMS's ability to ensure that nursing homes meet federal requirements for residents to be free from abuse. Specifically, GAO identified issues related to (1) referring abuse to law enforcement in a timely manner, (2) tracking abuse referrals, (3) defining what it means to substantiate an allegation of abuse—that is, the determination by the state survey agency that evidence supports the abuse allegation, and (4) sharing information with law enforcement. GAO made four recommendations to address these gaps and HHS concurred. As of November 2019, HHS had not implemented these recommendations.
2 20
t5 State and local governments face fiscal pressures when, taken as a whole, spending exceeds revenues . Fiscal pressures may reflect growth in selected expenditure categories without corresponding revenue growth or other spending reductions . For example, some programs may have spending that is defined or required in state law and must be funded annually, regardless of broader economic circumstances . Changes in the makeup of state and local government services, spending, and revenues may reflect economic or demographic changes .

{'datasets': [{'name': 'ccdv/arxiv-summarization',
   'models': {'bert': {0: {'rouge1': Score(precision=0.6829268292682927, recall=0.1407035175879397, fmeasure=0.23333333333333334),
      'rouge2': Score(precision=0.25, recall=0.050505050505050504, fmeasure=0.08403361344537816),
      'rougeL': Score(precision=0.5121951219512195, recall=0.10552763819095477, fmeasure=0.175)},
     10: {'rouge1': Score(precision=0.4, recall=0.16, fmeasure=0.22857142857142856),
      'rouge2': Score(precision=0.06896551724137931, recall=0.02702702702702703, fmeasure=0.03883495145631068),
      'rougeL': Score(precision=0.23333333333333334, recall=0.09333333333333334, fmeasure=0.13333333333333333)},
     20: {'rouge1': Score(precision=0.4791666666666667, recall=0.15862068965517243, fmeasure=0.2383419689119171),
      'rouge2': Score(precision=0.0851063829787234, recall=0.027777777777777776, fmeasure=0.041884816753926704),
      'rougeL': Score(precision=0.2916666666666667, recall=0.09655172413793103, fmeasure=0.14507772020725387)}},
    'pegasus': {0: {'rouge1': Score(precision=0.42857142857142855, recall=0.21105527638190955, fmeasure=0.2828282828282828),
      'rouge2': Score(precision=0.14432989690721648, recall=0.0707070707070707, fmeasure=0.09491525423728812),
      'rougeL': Score(precision=0.2653061224489796, recall=0.1306532663316583, fmeasure=0.17508417508417512)},
     10: {'rouge1': Score(precision=0.21052631578947367, recall=0.26666666666666666, fmeasure=0.23529411764705882),
      'rouge2': Score(precision=0.07446808510638298, recall=0.0945945945945946, fmeasure=0.08333333333333333),
      'rougeL': Score(precision=0.12631578947368421, recall=0.16, fmeasure=0.1411764705882353)},
     20: {'rouge1': Score(precision=0.13793103448275862, recall=0.05517241379310345, fmeasure=0.07881773399014778),
      'rouge2': Score(precision=0.03508771929824561, recall=0.013888888888888888, fmeasure=0.01990049751243781),
      'rougeL': Score(precision=0.08620689655172414, recall=0.034482758620689655, fmeasure=0.04926108374384237)}},
    't5': {0: {'rouge1': Score(precision=0.4782608695652174, recall=0.1658291457286432, fmeasure=0.24626865671641787),
      'rouge2': Score(precision=0.16176470588235295, recall=0.05555555555555555, fmeasure=0.08270676691729323),
      'rougeL': Score(precision=0.30434782608695654, recall=0.10552763819095477, fmeasure=0.15671641791044777)},
     10: {'rouge1': Score(precision=0.2361111111111111, recall=0.22666666666666666, fmeasure=0.23129251700680273),
      'rouge2': Score(precision=0.028169014084507043, recall=0.02702702702702703, fmeasure=0.027586206896551724),
      'rougeL': Score(precision=0.1388888888888889, recall=0.13333333333333333, fmeasure=0.13605442176870747)},
     20: {'rouge1': Score(precision=0.46551724137931033, recall=0.18620689655172415, fmeasure=0.26600985221674883),
      'rouge2': Score(precision=0.08771929824561403, recall=0.034722222222222224, fmeasure=0.04975124378109452),
      'rougeL': Score(precision=0.22413793103448276, recall=0.0896551724137931, fmeasure=0.12807881773399013)}}}},
  {'name': 'ccdv/pubmed-summarization',
   'models': {'bert': {0: {'rouge1': Score(precision=0.4864864864864865, recall=0.1005586592178771, fmeasure=0.16666666666666669),
      'rouge2': Score(precision=0.16666666666666666, recall=0.033707865168539325, fmeasure=0.056074766355140186),
      'rougeL': Score(precision=0.35135135135135137, recall=0.07262569832402235, fmeasure=0.12037037037037038)},
     10: {'rouge1': Score(precision=0.5116279069767442, recall=0.08494208494208494, fmeasure=0.14569536423841056),
      'rouge2': Score(precision=0.14285714285714285, recall=0.023255813953488372, fmeasure=0.04),
      'rougeL': Score(precision=0.3023255813953488, recall=0.05019305019305019, fmeasure=0.08609271523178808)},
     20: {'rouge1': Score(precision=0.390625, recall=0.1404494382022472, fmeasure=0.2066115702479339),
      'rouge2': Score(precision=0.047619047619047616, recall=0.01694915254237288, fmeasure=0.025),
      'rougeL': Score(precision=0.21875, recall=0.07865168539325842, fmeasure=0.11570247933884299)}},
    'pegasus': {0: {'rouge1': Score(precision=0.5957446808510638, recall=0.1564245810055866, fmeasure=0.247787610619469),
      'rouge2': Score(precision=0.10869565217391304, recall=0.028089887640449437, fmeasure=0.044642857142857144),
      'rougeL': Score(precision=0.3404255319148936, recall=0.0893854748603352, fmeasure=0.1415929203539823)},
     10: {'rouge1': Score(precision=0.5882352941176471, recall=0.11583011583011583, fmeasure=0.1935483870967742),
      'rouge2': Score(precision=0.16, recall=0.031007751937984496, fmeasure=0.05194805194805195),
      'rougeL': Score(precision=0.39215686274509803, recall=0.07722007722007722, fmeasure=0.12903225806451613)},
     20: {'rouge1': Score(precision=0.3023255813953488, recall=0.21910112359550563, fmeasure=0.2540716612377851),
      'rouge2': Score(precision=0.0625, recall=0.04519774011299435, fmeasure=0.05245901639344262),
      'rougeL': Score(precision=0.14728682170542637, recall=0.10674157303370786, fmeasure=0.1237785016286645)}},
    't5': {0: {'rouge1': Score(precision=0.42105263157894735, recall=0.1787709497206704, fmeasure=0.25098039215686274),
      'rouge2': Score(precision=0.12, recall=0.05056179775280899, fmeasure=0.07114624505928853),
      'rougeL': Score(precision=0.2631578947368421, recall=0.11173184357541899, fmeasure=0.15686274509803919)},
     10: {'rouge1': Score(precision=0.65, recall=0.05019305019305019, fmeasure=0.09318996415770607),
      'rouge2': Score(precision=0.3684210526315789, recall=0.027131782945736434, fmeasure=0.05054151624548737),
      'rougeL': Score(precision=0.35, recall=0.02702702702702703, fmeasure=0.05017921146953406)},
     20: {'rouge1': Score(precision=0.3684210526315789, recall=0.07865168539325842, fmeasure=0.12962962962962962),
      'rouge2': Score(precision=0.08108108108108109, recall=0.01694915254237288, fmeasure=0.028037383177570097),
      'rougeL': Score(precision=0.21052631578947367, recall=0.0449438202247191, fmeasure=0.07407407407407407)}}}},
  {'name': 'ccdv/govreport-summarization',
   'models': {'bert': {0: {'rouge1': Score(precision=0.5319148936170213, recall=0.04854368932038835, fmeasure=0.08896797153024912),
      'rouge2': Score(precision=0.2391304347826087, recall=0.021400778210116732, fmeasure=0.03928571428571429),
      'rougeL': Score(precision=0.40425531914893614, recall=0.036893203883495145, fmeasure=0.06761565836298933)},
     10: {'rouge1': Score(precision=0.8888888888888888, recall=0.037209302325581395, fmeasure=0.07142857142857142),
      'rouge2': Score(precision=0.5, recall=0.020186335403726708, fmeasure=0.03880597014925373),
      'rougeL': Score(precision=0.7407407407407407, recall=0.031007751937984496, fmeasure=0.059523809523809514)},
     20: {'rouge1': Score(precision=0.7192982456140351, recall=0.0740072202166065, fmeasure=0.1342062193126023),
      'rouge2': Score(precision=0.2857142857142857, recall=0.028933092224231464, fmeasure=0.05254515599343186),
      'rougeL': Score(precision=0.49122807017543857, recall=0.05054151624548736, fmeasure=0.09165302782324058)}},
    'pegasus': {0: {'rouge1': Score(precision=0.4189189189189189, recall=0.06019417475728155, fmeasure=0.10526315789473684),
      'rouge2': Score(precision=0.0684931506849315, recall=0.009727626459143969, fmeasure=0.017035775127768313),
      'rougeL': Score(precision=0.22972972972972974, recall=0.03300970873786408, fmeasure=0.05772495755517827)},
     10: {'rouge1': Score(precision=0.7294117647058823, recall=0.09612403100775194, fmeasure=0.16986301369863013),
      'rouge2': Score(precision=0.39285714285714285, recall=0.05124223602484472, fmeasure=0.09065934065934066),
      'rougeL': Score(precision=0.5176470588235295, recall=0.06821705426356589, fmeasure=0.12054794520547944)},
     20: {'rouge1': Score(precision=0.5959595959595959, recall=0.10649819494584838, fmeasure=0.1807044410413476),
      'rouge2': Score(precision=0.15306122448979592, recall=0.027124773960216998, fmeasure=0.046082949308755755),
      'rougeL': Score(precision=0.35353535353535354, recall=0.0631768953068592, fmeasure=0.10719754977029096)}},
    't5': {0: {'rouge1': Score(precision=0.6029411764705882, recall=0.07961165048543689, fmeasure=0.14065180102915953),
      'rouge2': Score(precision=0.19402985074626866, recall=0.02529182879377432, fmeasure=0.044750430292598974),
      'rougeL': Score(precision=0.35294117647058826, recall=0.04660194174757282, fmeasure=0.0823327615780446)},
     10: {'rouge1': Score(precision=0.8615384615384616, recall=0.08682170542635659, fmeasure=0.15774647887323942),
      'rouge2': Score(precision=0.609375, recall=0.06055900621118013, fmeasure=0.11016949152542373),
      'rougeL': Score(precision=0.6461538461538462, recall=0.06511627906976744, fmeasure=0.11830985915492957)},
     20: {'rouge1': Score(precision=0.5526315789473685, recall=0.07581227436823104, fmeasure=0.13333333333333333),
      'rouge2': Score(precision=0.22666666666666666, recall=0.03074141048824593, fmeasure=0.05414012738853503),
      'rougeL': Score(precision=0.39473684210526316, recall=0.05415162454873646, fmeasure=0.09523809523809523)}}}}]}

In [ ]:
rows = []
for dataset in results['datasets']:
    dataset_name = dataset['name']
    for model_name, indices in dataset['models'].items():
        for index, scores in indices.items():
            rouge1_scores = scores['rouge1']
            rouge2_scores = scores['rouge2']
            rougeL_scores = scores['rougeL']
            rows.append({
                'Dataset': dataset_name,
                'Model': model_name,
                'Index': index,
                'Rouge1_Precision': rouge1_scores[0],
                'Rouge1_Recall': rouge1_scores[1],
                'Rouge1_FMeasure': rouge1_scores[2],
                'Rouge2_Precision': rouge2_scores[0],
                'Rouge2_Recall': rouge2_scores[1],
                'Rouge2_FMeasure': rouge2_scores[2],
                'RougeL_Precision': rougeL_scores[0],
                'RougeL_Recall': rougeL_scores[1],
                'RougeL_FMeasure': rougeL_scores[2],
            })
df1 = pd.DataFrame(rows)

In [ ]:
gdfs1 = df1.groupby(by=["Dataset", "Model"])
desc_stats1 = {}
for i, gdf in gdfs1:
    desc_stats1[i] = gdf.describe()
keys = list(desc_stats1.keys())
keys

[('ccdv/arxiv-summarization', 'bert'),
 ('ccdv/arxiv-summarization', 'pegasus'),
 ('ccdv/arxiv-summarization', 't5'),
 ('ccdv/govreport-summarization', 'bert'),
 ('ccdv/govreport-summarization', 'pegasus'),
 ('ccdv/govreport-summarization', 't5'),
 ('ccdv/pubmed-summarization', 'bert'),
 ('ccdv/pubmed-summarization', 'pegasus'),
 ('ccdv/pubmed-summarization', 't5')]

In [ ]:
desc_stats1[('ccdv/pubmed-summarization', 't5')]

,Index,Rouge1_Precision,Rouge1_Recall,Rouge1_FMeasure,Rouge2_Precision,Rouge2_Recall,Rouge2_FMeasure,RougeL_Precision,RougeL_Recall,RougeL_FMeasure
count,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
mean,10.0,0.479825,0.102539,0.157933,0.189834,0.031548,0.049908,0.274561,0.061234,0.093705
std,10.0,0.149707,0.067535,0.082615,0.155880,0.017236,0.021561,0.070433,0.044640,0.055986
min,0.0,0.368421,0.050193,0.093190,0.081081,0.016949,0.028037,0.210526,0.027027,0.050179
25%,5.0,0.394737,0.064422,0.111410,0.100541,0.022040,0.039289,0.236842,0.035985,0.062127
50%,10.0,0.421053,0.078652,0.129630,0.120000,0.027132,0.050542,0.263158,0.044944,0.074074
75%,15.0,0.535526,0.128711,0.190305,0.244211,0.038847,0.060844,0.306579,0.078338,0.115468
max,20.0,0.650000,0.178771,0.250980,0.368421,0.050562,0.071146,0.350000,0.111732,0.156863

# LangChain Testing (Don't need to run)
___________________________________________

In [ ]:
!pip install langchain huggingface_hub --quiet

In [ ]:
pipe = pipeline("summarization", model="facebook/bart-large-cnn")
hf = HuggingFacePipeline(pipeline=pipe)
hf

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

HuggingFacePipeline(pipeline=<transformers.pipelines.text2text_generation.SummarizationPipeline object at 0x792222bfc250>, model_id='facebook/bart-large-cnn')

In [ ]:
test_article = str(datasets[0]['test'][0]['article']) + "\nSummary:\n"

In [ ]:
bart_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")

In [ ]:
tokens = tokenizer.tokenize(test_article)
print(f"Total Tokens: {len(tokens)}")

Total Tokens: 8052

In [ ]:
!pip install --upgrade --quiet langchain-text-splitters tiktoken

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.2 MB/s eta 0:00:00

In [ ]:
len(tokenizer.tokenize(f"Summarize the following chunk of an article:\n\nSummary:\n"))

15

In [ ]:
text_splitter = TokenTextSplitter(chunk_size=497, chunk_overlap=64)

texts = text_splitter.split_text(test_article)
for text in texts:
  print(len(tokenizer.tokenize(text)))

497
497
497
497
497
497
497
497
497
497
497
497
497
497
497
497
497
497
258

In [ ]:
summary = []
for text in texts:
  prompt = f"Summarize the following chunk of an article:\n{text}\nSummary:\n"
  input_ids = tokenizer(prompt, return_tensors="pt").input_ids
  output = bart_model.generate(input_ids, max_new_tokens = int(512/len(texts)))[0]
  summary.append(tokenizer.decode(output, skip_special_tokens=True))
summary

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (27). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 27, its default value.
  warnings.warn(

['For about 20 years the problem of properties of short - term changes of solar activity has been considered extensively. The periodicities',
 'During 1964 - 2000 the sunspot number wavelet power of periods less than one year shows a cyclic evolution with the',
 'The authors concluded that the length of this period is variable and the reason of the periodicity is still not understood.',
 'The bt method can be used to verify a reality of peaks which are computed using a method giving the better resolution.',
 'The method of the diagnosis of an echo - effect in the power spectrum ( de) consists in an analysis of a period',
 'The de method analyses raw estimators of the power spectrum. The fisher test checks the null hypothesis that the time series is',
 'Summarize the following chunk of an article: The index @xmath44 indicates successive parts of the cosinus function',
 'Summarize the following chunk of an article. The index @xmath65 describes a percentage of the contribution of the',
 'The de method can unambiguously decide about the existence of the considered periodicity in the given time series. It enables',
 'In this paper the sunspot activity data ( august 1923 - october 1933 ) provided by the greenwich photohel',
 'The time series for the northern hemisphere @xmath88 is shown. The prominent peak falls at 17 rotations interval (',
 'The periodogram of the time series @xmath101 has two significant peaks the first at 15.2 and the second',
 'The lomb - scargle periodograms for the both time series have a peak at 158.8 days which stands',
 'Two curves @xmath121 and @x Math122 are plotted. The value of @x math65 for the time',
 'The periodicity at about 155 days is a harmonic of the periodicity from the interval of @xmath1 $ ]',
 'The 154 - 158-day period could be the third harmonic of the 1.3-year ( 475-day )',
 'The dispersion of these points is 10 and it is difficult to find even few points which oscillate around the value of',
 'The time series @xmath89 is zero for the fluctuations from the whole solar cycle and it is almost zero ( @',
 'A new method of the detection of statistically significant peaks of the periodograms enables one to identify aliases in the periodogram.']

In [ ]:
summary = " ".join(summary)
input_ids = tokenizer(summary, return_tensors="pt").input_ids
output = bart_model.generate(input_ids, max_new_tokens = 512)[0]
gen_summ = tokenizer.decode(output, skip_special_tokens=True)
scorer.score(datasets[0]['test'][0]['abstract'], gen_summ)

{'rouge1': Score(precision=0.5319148936170213, recall=0.12562814070351758, fmeasure=0.20325203252032517),
 'rouge2': Score(precision=0.1956521739130435, recall=0.045454545454545456, fmeasure=0.0737704918032787),
 'rougeL': Score(precision=0.3617021276595745, recall=0.08542713567839195, fmeasure=0.13821138211382114)}

# Final Testing (Run)
____________________________________________

In [ ]:
bert_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
bert_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
pegasus_model = AutoModelForSeq2SeqLM.from_pretrained("google/pegasus-large")
pegasus_tokenizer = AutoTokenizer.from_pretrained("google/pegasus-large")
t5_model = AutoModelForSeq2SeqLM.from_pretrained("Falconsai/text_summarization")
t5_tokenizer = AutoTokenizer.from_pretrained("Falconsai/text_summarization")

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-large and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
device = "cuda"
bert_model.to(device)
pegasus_model.to(device)
t5_model.to(device)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [ ]:
test_indexes = list(range(0, 500, 10))
small_text_splitter = TokenTextSplitter(chunk_size=497, chunk_overlap=64)
large_text_splitter = TokenTextSplitter(chunk_size=990, chunk_overlap=128)

In [ ]:
stored_data = {"datasets": [{"name": "ccdv/arxiv-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}, {"name": "ccdv/pubmed-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}, {"name": "ccdv/govreport-summarization", "models": {"bert": {}, "pegasus": {}, "t5": {}}}]}

In [ ]:

for i, dataset in enumerate(datasets):
  if i == 2:
    article_text = "report"
    sum_text = "summary"
  else:
    article_text = "article"
    sum_text = "abstract"
  for ex_idx in tqdm(test_indexes, desc=f"Dataset{i+1}"):
    article = dataset['test'][ex_idx][article_text]
    true_summary = dataset['test'][ex_idx][sum_text]
    chunks = small_text_splitter.split_text(article)
    summaries = {"bert":[], "pegasus":[], "t5":[]}
    for j, chunk in enumerate(chunks):
      prompt = f"Summarize the following chunk of an article:\n{chunk}\nSummary:\n"
      bert_input_ids = bert_tokenizer(prompt, return_tensors="pt").input_ids.to(device)
      bert_output = bert_model.generate(bert_input_ids, max_new_tokens = int(512/len(chunks)))[0]
      summaries['bert'].append(bert_tokenizer.decode(bert_output, skip_special_tokens=True))
      pegasus_input_ids = pegasus_tokenizer(prompt, return_tensors="pt").input_ids.to(device)
      pegasus_output = pegasus_model.generate(pegasus_input_ids, max_new_tokens = int(512/len(chunks)))[0]
      summaries['pegasus'].append(pegasus_tokenizer.decode(pegasus_output, skip_special_tokens=True))
      t5_input_ids = t5_tokenizer(prompt, return_tensors="pt").input_ids.to(device)
      t5_output = t5_model.generate(t5_input_ids, max_new_tokens = int(512/len(chunks)))[0]
      summaries['t5'].append(t5_tokenizer.decode(t5_output, skip_special_tokens=True))
    bert_summary = " ".join(summaries['bert'])
    bert_input_ids = bert_tokenizer(bert_summary, return_tensors="pt").input_ids.to(device)
    bert_output = bert_model.generate(bert_input_ids, max_new_tokens = 512)[0]
    bert_gen_summ = bert_tokenizer.decode(bert_output, skip_special_tokens=True)
    pegasus_summary = " ".join(summaries['pegasus'])
    pegasus_input_ids = pegasus_tokenizer(pegasus_summary, return_tensors="pt").input_ids.to(device)
    pegasus_output = pegasus_model.generate(pegasus_input_ids, max_new_tokens = 512)[0]
    pegasus_gen_summ = pegasus_tokenizer.decode(pegasus_output, skip_special_tokens=True)
    t5_summary = " ".join(summaries['t5'])
    t5_input_ids = t5_tokenizer(t5_summary, return_tensors="pt").input_ids.to(device)
    t5_output = t5_model.generate(t5_input_ids, max_new_tokens = 512)[0]
    t5_gen_summ = t5_tokenizer.decode(t5_output, skip_special_tokens=True)
    stored_data["datasets"][i]["models"]["bert"][ex_idx] = scorer.score(true_summary, bert_gen_summ)
    stored_data["datasets"][i]["models"]["pegasus"][ex_idx] = scorer.score(true_summary, pegasus_gen_summ)
    stored_data["datasets"][i]["models"]["t5"][ex_idx] = scorer.score(true_summary, t5_gen_summ)
with open('model_data.json', 'w') as f:
  json.dump(stored_data, f)
files.download('model_data.json')

Dataset1:   0%|          | 0/50 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (43). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 43, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (8). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 8, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (37). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 37, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (33). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 33, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (35). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 35, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (22). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 22, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (16). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 16, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (21). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 21, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (17). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 17, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (26). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 26, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (40). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 40, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (18). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 18, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (29). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 29, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (10). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 10, its default value.
  warnings.warn(

Dataset2:   0%|          | 0/50 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (15). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 15, its default value.
  warnings.warn(

Dataset3:   0%|          | 0/50 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (23). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 23, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (14). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 14, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (9). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 9, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (20). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 20, its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1399: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (6). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 6, its default value.
  warnings.warn(

In [ ]:
import pandas as pd
rows = []
for dataset in stored_data['datasets']:
    dataset_name = dataset['name']
    for model_name, indices in dataset['models'].items():
        for index, scores in indices.items():
            rouge1_scores = scores['rouge1']
            rouge2_scores = scores['rouge2']
            rougeL_scores = scores['rougeL']
            rows.append({
                'Dataset': dataset_name,
                'Model': model_name,
                'Index': index,
                'Rouge1_Precision': rouge1_scores[0],
                'Rouge1_Recall': rouge1_scores[1],
                'Rouge1_FMeasure': rouge1_scores[2],
                'Rouge2_Precision': rouge2_scores[0],
                'Rouge2_Recall': rouge2_scores[1],
                'Rouge2_FMeasure': rouge2_scores[2],
                'RougeL_Precision': rougeL_scores[0],
                'RougeL_Recall': rougeL_scores[1],
                'RougeL_FMeasure': rougeL_scores[2],
            })
df = pd.DataFrame(rows)
df.to_csv('model_data.csv', index=False)
files.download('model_data.csv')

In [ ]:
gdfs = df.groupby(by=["Dataset", "Model"])

In [ ]:
desc_stats = {}
for i, gdf in gdfs:
    desc_stats[i] = gdf.describe()

In [ ]:
keys = list(desc_stats.keys())
keys

[('ccdv/arxiv-summarization', 'bert'),
 ('ccdv/arxiv-summarization', 'pegasus'),
 ('ccdv/arxiv-summarization', 't5'),
 ('ccdv/govreport-summarization', 'bert'),
 ('ccdv/govreport-summarization', 'pegasus'),
 ('ccdv/govreport-summarization', 't5'),
 ('ccdv/pubmed-summarization', 'bert'),
 ('ccdv/pubmed-summarization', 'pegasus'),
 ('ccdv/pubmed-summarization', 't5')]

In [ ]:
desc_stats[('ccdv/pubmed-summarization', 't5')]

,Index,Rouge1_Precision,Rouge1_Recall,Rouge1_FMeasure,Rouge2_Precision,Rouge2_Recall,Rouge2_FMeasure,RougeL_Precision,RougeL_Recall,RougeL_FMeasure
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,245.000000,0.443864,0.170153,0.226915,0.126483,0.054377,0.068317,0.286691,0.114209,0.149441
std,145.773797,0.142650,0.112642,0.090109,0.098388,0.095064,0.080368,0.101201,0.104542,0.082218
min,0.000000,0.100000,0.047244,0.064171,0.000000,0.000000,0.000000,0.083333,0.039370,0.053476
25%,122.500000,0.350870,0.111342,0.169019,0.056818,0.019648,0.027663,0.205834,0.072067,0.105131
50%,245.000000,0.440339,0.137362,0.205689,0.097407,0.029680,0.042283,0.288312,0.082063,0.123813
75%,367.500000,0.574364,0.189211,0.273917,0.186921,0.061157,0.077794,0.358154,0.118856,0.159716
max,490.000000,0.640000,0.765957,0.585366,0.400000,0.652174,0.495868,0.520000,0.744681,0.569106

In [ ]:
for key in keys:
  table = desc_stats[key]
  r1 = table.loc['mean', 'Rouge1_FMeasure']
  r2 = table.loc['mean', 'Rouge2_FMeasure']
  rl = table.loc['mean', 'RougeL_FMeasure']
  print(f"{key}: {round(r1, 2)} / {round(r2, 2)} / {round(rl, 2)}")

('ccdv/arxiv-summarization', 'bert'): 0.26 / 0.07 / 0.16
('ccdv/arxiv-summarization', 'pegasus'): 0.33 / 0.09 / 0.18
('ccdv/arxiv-summarization', 't5'): 0.17 / 0.03 / 0.12
('ccdv/govreport-summarization', 'bert'): 0.12 / 0.05 / 0.09
('ccdv/govreport-summarization', 'pegasus'): 0.34 / 0.12 / 0.16
('ccdv/govreport-summarization', 't5'): 0.15 / 0.05 / 0.1
('ccdv/pubmed-summarization', 'bert'): 0.24 / 0.07 / 0.15
('ccdv/pubmed-summarization', 'pegasus'): 0.28 / 0.09 / 0.16
('ccdv/pubmed-summarization', 't5'): 0.23 / 0.07 / 0.15

# Other
____________________________________________________

Calculating approximate average token length of articles

In [ ]:
for j in range(3):
  l = []
  for i in range(0,6400):
    if j == 2:
      article = datasets[j]['test'][i]['report']
    else:
      article = datasets[j]['test'][i]['article']
    num_tokens = len(bert_tokenizer(article).input_ids)
    l.append(num_tokens)
    if j == 2 and i == 900:
      break
  print(sum(l)/len(l))

8540.76265625
4080.09125
9204.471698113208